name: conda_env
channels:
  - conda-forge
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - libsqlite
  - libzlib
  - ncurses
  - openssl
  - pip
  - pydash=8.0.1=pyhca7485f_0
  - python
  - readline
  - setuptools
  - tk=8.6.13
  - typing_extensions
  - tzdata
  - wheel
  - xz
